package cn.edu.cqut.weknow.po;

public class Feedbacks {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbacks.id
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbacks.userId
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbacks.content
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedbacks.sendTime
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    private String sendtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbacks.id
     *
     * @return the value of feedbacks.id
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbacks.id
     *
     * @param id the value for feedbacks.id
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbacks.userId
     *
     * @return the value of feedbacks.userId
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbacks.userId
     *
     * @param userid the value for feedbacks.userId
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbacks.content
     *
     * @return the value of feedbacks.content
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbacks.content
     *
     * @param content the value for feedbacks.content
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedbacks.sendTime
     *
     * @return the value of feedbacks.sendTime
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public String getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedbacks.sendTime
     *
     * @param sendtime the value for feedbacks.sendTime
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public void setSendtime(String sendtime) {
        this.sendtime = sendtime == null ? null : sendtime.trim();
    }
}