package cn.edu.cqut.weknow.po;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.type
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.imageUrl
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    private String imageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.audioUrl
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    private String audiourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.videoUrl
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    private String videourl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.uploadTime
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    private String uploadtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.uploadIp
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    private String uploadip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.authorId
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    private Integer authorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.position
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.addressCode
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    private String addresscode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.type
     *
     * @return the value of news.type
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.type
     *
     * @param type the value for news.type
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.imageUrl
     *
     * @return the value of news.imageUrl
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.imageUrl
     *
     * @param imageurl the value for news.imageUrl
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.audioUrl
     *
     * @return the value of news.audioUrl
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public String getAudiourl() {
        return audiourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.audioUrl
     *
     * @param audiourl the value for news.audioUrl
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public void setAudiourl(String audiourl) {
        this.audiourl = audiourl == null ? null : audiourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.videoUrl
     *
     * @return the value of news.videoUrl
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public String getVideourl() {
        return videourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.videoUrl
     *
     * @param videourl the value for news.videoUrl
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public void setVideourl(String videourl) {
        this.videourl = videourl == null ? null : videourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.uploadTime
     *
     * @return the value of news.uploadTime
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public String getUploadtime() {
        return uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.uploadTime
     *
     * @param uploadtime the value for news.uploadTime
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public void setUploadtime(String uploadtime) {
        this.uploadtime = uploadtime == null ? null : uploadtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.uploadIp
     *
     * @return the value of news.uploadIp
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public String getUploadip() {
        return uploadip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.uploadIp
     *
     * @param uploadip the value for news.uploadIp
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public void setUploadip(String uploadip) {
        this.uploadip = uploadip == null ? null : uploadip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.authorId
     *
     * @return the value of news.authorId
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public Integer getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.authorId
     *
     * @param authorid the value for news.authorId
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.position
     *
     * @return the value of news.position
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.position
     *
     * @param position the value for news.position
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.addressCode
     *
     * @return the value of news.addressCode
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public String getAddresscode() {
        return addresscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.addressCode
     *
     * @param addresscode the value for news.addressCode
     *
     * @mbggenerated Wed Aug 30 08:56:41 CST 2017
     */
    public void setAddresscode(String addresscode) {
        this.addresscode = addresscode == null ? null : addresscode.trim();
    }
}