package cn.edu.cqut.weknow.po;

public class NewsContributions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_contributions.id
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_contributions.userId
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_contributions.newsId
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    private Integer newsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_contributions.type
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    private Byte type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_contributions.id
     *
     * @return the value of news_contributions.id
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_contributions.id
     *
     * @param id the value for news_contributions.id
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_contributions.userId
     *
     * @return the value of news_contributions.userId
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_contributions.userId
     *
     * @param userid the value for news_contributions.userId
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_contributions.newsId
     *
     * @return the value of news_contributions.newsId
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public Integer getNewsid() {
        return newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_contributions.newsId
     *
     * @param newsid the value for news_contributions.newsId
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public void setNewsid(Integer newsid) {
        this.newsid = newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_contributions.type
     *
     * @return the value of news_contributions.type
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_contributions.type
     *
     * @param type the value for news_contributions.type
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }
}