package cn.edu.cqut.weknow.po;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nick
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.userName
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.phone
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.avatarUrl
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    private String avatarurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.registerTime
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    private String registertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.registerIp
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    private String registerip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.personalizedSignature
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    private String personalizedsignature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.note
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nick
     *
     * @return the value of users.nick
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nick
     *
     * @param nick the value for users.nick
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.userName
     *
     * @return the value of users.userName
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.userName
     *
     * @param username the value for users.userName
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.phone
     *
     * @return the value of users.phone
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.phone
     *
     * @param phone the value for users.phone
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.avatarUrl
     *
     * @return the value of users.avatarUrl
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public String getAvatarurl() {
        return avatarurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.avatarUrl
     *
     * @param avatarurl the value for users.avatarUrl
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public void setAvatarurl(String avatarurl) {
        this.avatarurl = avatarurl == null ? null : avatarurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.registerTime
     *
     * @return the value of users.registerTime
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public String getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.registerTime
     *
     * @param registertime the value for users.registerTime
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public void setRegistertime(String registertime) {
        this.registertime = registertime == null ? null : registertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.registerIp
     *
     * @return the value of users.registerIp
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public String getRegisterip() {
        return registerip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.registerIp
     *
     * @param registerip the value for users.registerIp
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public void setRegisterip(String registerip) {
        this.registerip = registerip == null ? null : registerip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.personalizedSignature
     *
     * @return the value of users.personalizedSignature
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public String getPersonalizedsignature() {
        return personalizedsignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.personalizedSignature
     *
     * @param personalizedsignature the value for users.personalizedSignature
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public void setPersonalizedsignature(String personalizedsignature) {
        this.personalizedsignature = personalizedsignature == null ? null : personalizedsignature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.note
     *
     * @return the value of users.note
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.note
     *
     * @param note the value for users.note
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}