package cn.edu.cqut.weknow.po;

public class UserAuths {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auths.id
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auths.userId
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auths.identifyType
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    private String identifytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auths.identifier
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    private String identifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auths.credential
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    private String credential;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auths.verified
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    private Boolean verified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auths.loginTime
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    private String logintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_auths.loginIp
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    private String loginip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auths.id
     *
     * @return the value of user_auths.id
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auths.id
     *
     * @param id the value for user_auths.id
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auths.userId
     *
     * @return the value of user_auths.userId
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auths.userId
     *
     * @param userid the value for user_auths.userId
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auths.identifyType
     *
     * @return the value of user_auths.identifyType
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public String getIdentifytype() {
        return identifytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auths.identifyType
     *
     * @param identifytype the value for user_auths.identifyType
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public void setIdentifytype(String identifytype) {
        this.identifytype = identifytype == null ? null : identifytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auths.identifier
     *
     * @return the value of user_auths.identifier
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auths.identifier
     *
     * @param identifier the value for user_auths.identifier
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auths.credential
     *
     * @return the value of user_auths.credential
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public String getCredential() {
        return credential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auths.credential
     *
     * @param credential the value for user_auths.credential
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public void setCredential(String credential) {
        this.credential = credential == null ? null : credential.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auths.verified
     *
     * @return the value of user_auths.verified
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public Boolean getVerified() {
        return verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auths.verified
     *
     * @param verified the value for user_auths.verified
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auths.loginTime
     *
     * @return the value of user_auths.loginTime
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public String getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auths.loginTime
     *
     * @param logintime the value for user_auths.loginTime
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public void setLogintime(String logintime) {
        this.logintime = logintime == null ? null : logintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_auths.loginIp
     *
     * @return the value of user_auths.loginIp
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public String getLoginip() {
        return loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_auths.loginIp
     *
     * @param loginip the value for user_auths.loginIp
     *
     * @mbggenerated Mon Aug 28 12:41:24 CST 2017
     */
    public void setLoginip(String loginip) {
        this.loginip = loginip == null ? null : loginip.trim();
    }
}