package cn.edu.cqut.weknow.po.mapper;

import cn.edu.cqut.weknow.po.Admins;
import cn.edu.cqut.weknow.po.AdminsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int countByExample(AdminsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int deleteByExample(AdminsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int insert(Admins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int insertSelective(Admins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    List<Admins> selectByExample(AdminsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    Admins selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") Admins record, @Param("example") AdminsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int updateByExample(@Param("record") Admins record, @Param("example") AdminsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int updateByPrimaryKeySelective(Admins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int updateByPrimaryKey(Admins record);
}