package cn.edu.cqut.weknow.po.mapper;

import cn.edu.cqut.weknow.po.NewsContributions;
import cn.edu.cqut.weknow.po.NewsContributionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsContributionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_contributions
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int countByExample(NewsContributionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_contributions
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int deleteByExample(NewsContributionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_contributions
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_contributions
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int insert(NewsContributions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_contributions
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int insertSelective(NewsContributions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_contributions
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    List<NewsContributions> selectByExample(NewsContributionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_contributions
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    NewsContributions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_contributions
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") NewsContributions record, @Param("example") NewsContributionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_contributions
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int updateByExample(@Param("record") NewsContributions record, @Param("example") NewsContributionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_contributions
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int updateByPrimaryKeySelective(NewsContributions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_contributions
     *
     * @mbggenerated Wed Aug 23 09:33:29 CST 2017
     */
    int updateByPrimaryKey(NewsContributions record);
}